### ISSUE TITLE
No "Full Build" button

### ISSUE THREAD

**Issue by trollusk** [QodotPlugin/Qodot#19]
I'm using Godot 4, the version with .NET support, and the latest Qodot from github. The plugin shows up as enabled in project settings, and QodotMap and other nodes can be created, but there are no "Full Build" or other buttons at the top of the viewport. Also loading the project produces the following error message in Output:

`res://addons/qodot/src/qodot_plugin.gd:36 - Invalid call. Nonexistent function 'new' in base 'CSharpScript'.`

**Comment by DeerTears** [comment]
Yep. This is because the WAD import script referenced in that line of the plugin is trying to be instantiated, but it's returning `null` instead of `CSharpScript`. It's weird because most of the plugin works otherwise, but the GUI stuff fails. We recently pushed some changes that finally fixed most of the issues with RC3 through Stable, but there's one regression we haven't figured out yet which is breaking `QuakeWadImportPlugin.cs` for Stable.

**tldr;** we know what to fix, it will be fixed soon. 😅 Help would be appreciated, I'm writing another issue for the script which I'll post in a minute.

In the meantime, you can try backing up your project and going back to [Godot 4.0 RC2 mono](https://downloads.tuxfamily.org/godotengine/4.0/rc2/mono/). As of writing the Assetlib version still works with RC2 without any changes in Qodot's functionality.

**Comment by DeerTears** [comment]
@trollusk What version of .NET have you installed? Have you tried installing .NET 7.0 and then opening the project again? https://dotnet.microsoft.com/en-us/download

**Comment by trollusk** [comment]
I've installed .NET 7.0 and rebooted. Unfortunately it still gives the same error message.

**Comment by patch7331** [comment]
To add onto this, if you have already have a .csproj file in your directory the 'Create C# Solution' option does not appear in the editor. In my case, I had already created one in Godot 3.5, I had to delete it for the option to re-appear. This allowed me to 'Full Build' again.
