### ISSUE TITLE
Qodot without .net

### ISSUE THREAD

**Issue by CachorroVoador** [QodotPlugin/Qodot#35]
Good morning!

My doubt is that someday we will have a qodot version for godot 4 that won't need the .net version? Or some port to c++?

**Comment by EMBYRDEV** [comment]
I did have a C++ port but we didnt have the time to setup and maintain a build server for distributing binaries for all platforms.

I ported to C# because Godot has plans to integrate C# into the main editor so that we wont have 2 seperate engine downloads. So this wont be a problem for too long.

I also made a GDScript version of the plugin at the time and it was something like 10x slower when tested so we decided against it.

![image](https://user-images.githubusercontent.com/20043270/232896442-1e0f6b7d-161c-4cb5-b0f1-275ab99001ce.png)

https://godotengine.org/article/godot-4-0-sets-sail/
