### ISSUE TITLE
Replace `QodotUtil.CATEGORY_STRING` with `@export_group`

### ISSUE THREAD

**Issue by bpseudopod** [QodotPlugin/Qodot#40]
Godot 4 offers the `@export_group` annotation for grouping related exports together. As of now, Qodot uses dummy String exports, the values of which are:
```gdscript
const CATEGORY_STRING := '----------------------------------------------------------------'
```
Speaking from my experience as a Qodot beginner, these dummy values are confusing, as it's not immediately clear that they only serve an aesthetic/organizational purpose. Being unclear, they come off less as a usability aid and more as clutter.

Qodot 4 supplies the `@export_group` annotation, which provides a native way to separate exports in the inspector. Export groups also offer the ability to fold exports, allowing the user to hide irrelevant properties.

In order to provide a better experience to beginners and experienced users alike, these dummy exports should be replaced with `@export_group` annotations. I'm willing to put in the work myself to do this.

**Comment by tinkerttoy** [comment]
When I wrote this issue, I had `qodot_fgd_class.gd` in mind, which has two categories with many members each. I just now took a look at the other usages of it. 

The other two uses of `CATEGORY_STRING` in Qodot, namely `qodot_fgd_point_class.gd` and `qodot_fgd_solid_class.gd`, are used to mark off categories that have one export each. In this case, I think it would make more sense to remove the dummy exports entirely, rather than converting them to categories with single members.
