### ISSUE TITLE
Invalid call. Nonexistent function 'build_def_text' in base 'Resource (QodotFGDSolidClass)' 

### ISSUE THREAD

**Issue by VincentHill** [QodotPlugin/Qodot#42]
When I try to export the FGD or create the Game Folder I get this error:
res://addons/qodot/src/resources/game-definitions/fgd/qodot_fgd_file.gd:52 - Invalid call. Nonexistent function 'build_def_text' in base 'Resource (QodotFGDSolidClass)'.
I tried a new project with just the addon and it still gives me the error. here is that project.
[QodotTest.zip](https://github.com/QodotPlugin/qodot-plugin/files/11544679/QodotTest.zip)

I using linux and my Godot is version:
v4.0.stable.mono.official [92bee43ad]

**Comment by Paragrimm** [comment]
I can confirm this. This is the same error I'm getting.

**Comment by mode777** [comment]
I'm getting the same error the latest version of Godot 4 (v4.0.3.stable.mono.official [5222a99f5])

So I decided to poke around a bit and found some really peculiar behaviour. So the method in question is implemented in QodotFGDClass and our entity is also of this type, so it should have the method.

I added some code to debug and the output is really peculiar

```python
func build_class_text() -> String:
	var res : String = ""

	for base_fgd in base_fgd_files:
		res += base_fgd.build_class_text()

	var entities = get_fgd_classes()
	for ent in entities:
		if ent.qodot_internal:
			continue
		if(ent is QodotFGDClass):
			for m in ent.get_method_list(): # Get all methods of current entity
				if(m.name == "build_def_text"):
					print(m) # If it prints, it has the method "build_def_text"...
			
			print("Has method: " + str(ent.has_method("build_def_text"))) # ...and this should be true
		else:
			print("ent is not fgdclass")
					
		var ent_text = ent.build_def_text() #Error occurs here
		res += ent_text
		if ent != entities[-1]:
			res += "\n"
	return res
```
Suprisingly this has the following output. 
```
Exporting FGD to C:/Users/z002f2au/Downloads/TrenchBroom-Win64-v2023.1-Release/games/Qodot/Qodot.fgd
{ "name": "build_def_text", "args": [], "default_args": [], "flags": 1, "id": 0, "return": { "name": "", "class_name": &"", "type": 4, "hint": 0, "hint_string": "", "usage": 6 } }
Has method: false
  res://addons/qodot/src/resources/game-definitions/fgd/qodot_fgd_file.gd:62 - Invalid call. Nonexistent function 'build_def_text' in base 'Resource (QodotFGDSolidClass)'.
```
So it does have the method but has_method returns false? Might this be a gdscript bug?

**Comment by GrauBlitz** [comment]
Can conform on `v4.1.beta3.mono.offical`

**Comment by mode777** [comment]
I added `@tool` on top of `qodot_fgd_class.gd` and now it works after restarting the editor /re-enabling the plugin. I'm not a 100% sure if this was the cause. Maybe someone can confirm. At least I can say that, if this error occurs the `_init` function of `qodot_fgd_solid_class` is not called. If it doesn't occur, it is called. Maybe this helps. https://github.com/QodotPlugin/Qodot/blob/45b1ffd1e1bb751390b63ca3dd4d2dd357af7874/addons/qodot/src/resources/game-definitions/fgd/qodot_fgd_class.gd#L1

**Comment by GelosoFederico** [comment]
> I added `@tool` on top of `qodot_fgd_class.gd` and now it works after restarting the editor /re-enabling the plugin. I'm not a 100% sure if this was the cause. Maybe someone can confirm. At least I can say that, if this error occurs the `_init` function of `qodot_fgd_solid_class` is not called. If it doesn't occur, it is called. Maybe this helps.
> 
> https://github.com/QodotPlugin/Qodot/blob/45b1ffd1e1bb751390b63ca3dd4d2dd357af7874/addons/qodot/src/resources/game-definitions/fgd/qodot_fgd_class.gd#L1
> 
> EDIT: There is one more change needed. The changes above would still not call the constructor thus not setting the `prefix` correctly. I needed to call ´ent._init()´ manually before calling `build_def_text` this works but it is of course quite ugly.

I might be doing something wrong, but I added only the @tool command and it didn't work with that, then I added the init for each ent, it worked, then reverted back and it continued to work... for some reason. I don't know if the init is doing something to the resource itself.

I'm on Godot 4.0.3.

**Comment by DeerTears** [comment]
@mode777 @GelosoFederico @GrauBlitz @Paragrimm @VincentHill I pushed a fix for this on the latest master branch. Try exporting a config after downloading the current state of the repo as a .zip and putting it in your project.

**Backup your project before you try updating Qodot**, I moved some entity definitions out of Qodot_fgd (you can add .tres files back into the array yourself) but barebones configs should at least build. Once I hear back that it's finally building configs for people, I'll restore the rest of the entity definitions.

**Comment by mode777** [comment]
Just tested it and it worked fine. Also added the missing definitions and my custom ones back in - still working. Due to the flaky behaviour of this bug I think we should wait for more confirmations. I'll test it on my Mac as well and report back.

**Comment by laurheth** [comment]
Tried the most recent version on my end (Windows, new project). Seems to be fixed for me as well.

**Comment by DeerTears** [comment]
@mode777 
> Just tested it and it worked fine. Also added the missing definitions and my custom ones back in - still working. Due to the flaky behaviour of this bug I think we should wait for more confirmations. I'll test it on my Mac as well and report back.
> 
> EDIT: Tested it on my mac and it worked like a charm. May I ask what the main cause for this problem was? The behaviour seemed very strange.

Somewhere Godot changed how its .tres files link subresources like scripts, materials, and meshes. Before it was just an index of [id=1] and [id=2], which was limited to all subresources within the resource.

Old Qodot_fgd.tres:
```
[ext_resource path="res://addons/qodot/game_definitions/fgd/base_classes/target_base_class.tres" type="Resource" id=1]
[ext_resource path="res://addons/qodot/game_definitions/fgd/solid_classes/func_group_solid_class.tres" type="Resource" id=2]
[ext_resource path="res://addons/qodot/game_definitions/fgd/point_classes/signal_point_class.tres" type="Resource" id=3]
[ext_resource path="res://addons/qodot/game_definitions/fgd/base_classes/targetname_base_class.tres" type="Resource" id=4]
[ext_resource path="res://addons/qodot/game_definitions/fgd/solid_classes/trigger_solid_class.tres" type="Resource" id=5]
```

New Qodot_fgd.tres:
```
[ext_resource type="Resource" path="res://addons/qodot/game_definitions/fgd/base_classes/target_base_class.tres" id="1"]
[ext_resource type="Resource" path="res://addons/qodot/game_definitions/fgd/solid_classes/func_group_solid_class.tres" id="2"]
[ext_resource type="Resource" path="res://addons/qodot/game_definitions/fgd/point_classes/signal_point_class.tres" id="3"]
[ext_resource type="Resource" uid="uid://ccdjpf5j25aua" path="res://addons/qodot/game_definitions/fgd/base_classes/targetname_base_class.tres" id="4"]
[ext_resource type="Resource" path="res://addons/qodot/game_definitions/fgd/solid_classes/trigger_solid_class.tres" id="5"]
```

It's such a tiny difference but those quotation marks around the id number is literally the only thing that has been modified by loading Qodot in the new version of the engine.

But if I make a brand new fgd .tres file, this is what it starts with:
```
[ext_resource type="Resource" uid="uid://c36hv0o6g0udo" path="res://addons/qodot/game_definitions/fgd/qodot_fgd.tres" id="1_oc0dk"]
[ext_resource type="Script" path="res://addons/qodot/src/resources/game-definitions/fgd/qodot_fgd_file.gd" id="1_svwqg"]
```
These days, when you generate a .tres file, it generates a type of string hash, and old .tres files are migrated to string equivalents of their indices: [id="1"] and [id="2"].

My hunch is that these strings are actually namespaces now, instead of just local indices within the resource file, so my best guess is that some subresources get swapped or overwritten by having conflicting names with one another. Keep in mind, all migrated resources were using id=1 and so on, so they all converted to id="1",

I have no evidence to suggest this is the case, but this is the only thing different about a .tres file that fails in this way. It that cannot invoke class methods and properties on scripts embedded a level deeper into its ext_resources. If all the IDs of its ext_resources are unique, everything is fine.

This actually could be reported to Godot as a migration issue with resources, but I'm too tired of dealing with this bug to make a minimum reproduction 😅 I'm only **assuming** you could reproduce it reliably by:
1. opening Godot 3.x
2. writing a `foo()` method in a script on a resource that prints to console or something
3. making a new resource, and embedding the original resource in an exported array
4. writing a function to accessing that array in code, and calling the `foo()` method on the original resource in the array
5. migrating the resources and scripts to Godot 4.x (modifying the script to be 4.x compatible does not change the ID values)
6. calling the new function, causing a similar `Invalid call.` error

**Comment by DeerTears** [comment]
This is definitely more detail than you needed, but it's late and I am happy to hear that it's fixed for people 😊 spread the word!
