### ISSUE TITLE
Unable to turn on addon

### ISSUE THREAD

**Issue by jvne2134** [QodotPlugin/Qodot#50]
Unable to load addon script from path: 'res://addons/Qodot-2.1.0/addons/qodot/src/qodot_plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/Qodot-2.1.0/addons/qodot/plugin.cfg' to prevent further errors.

**Comment by DeerTears** [comment]
Did you press "Build" in the top-right of the screen first, and do you have .NET SDK 7.0 installed? https://dotnet.microsoft.com/en-us/download

**Comment by DeerTears** [comment]
Ah hold on, you might need to move it out of the zip folder when you unpack it into your project. It should be `res://addons/qodot/` not `res://addons/Qodot-2.1.0/addons` as there are some hardcoded resource paths in the code.

Also, it helps to download the latest master rather than the latest release. As of writing master is getting a release soon to get everyone up to speed.

**Comment by DeerTears** [comment]
If you have any additional troubles, don't hesitate to make a new issue or ask on the Discord.
