### ISSUE TITLE
.map files are not exported in exports

### ISSUE THREAD

**Issue by itsmagu** [QodotPlugin/Qodot#51]
![bild](https://github.com/QodotPlugin/Qodot/assets/95685391/c10635b1-2265-4b53-8601-3b8e697df089)
When exporting a project that loads a map at runtime does not find the .map file.

![bild](https://github.com/QodotPlugin/Qodot/assets/95685391/a0198326-16c7-48ac-be4c-8cdb7a9c6a30)
In editor this works since the .map file exsists.

**Comment by EMBYRDEV** [comment]
This is normal intended behaviour of Godot.

You need to manually tell Godot to export other file types alongside the game.
![image](https://github.com/QodotPlugin/Qodot/assets/20043270/8ff55b50-adc3-4081-8b92-3b9704e026ba)

I'm not sure why you'd want to do this since the main purpose of runtime map building is for loading user mods but I'm sure you have your reasons!
