### ISSUE TITLE
func_groups are built as dynamic geometry

### ISSUE THREAD

**Issue by RealPlanet** [QodotPlugin/Qodot#74]
To my knowledge func_groups can't contain any entities, as a result, wouldn't it make more sense to build these as static geometry just like worldspawn?

Locally, I simply added ` || entity_definition.spawn_type == QodotFGDSolidClass.SpawnType.GROUP` to the if statement in `build_entity_mesh_instances()` if it's alright i can make a commit for it, unless there's a way to do this already.

**Comment by DeerTears** [comment]
Func groups in trenchbroom can contain entities, but the issue is that Qodot doesn't build their entity children as node children, even though there appears to be intended support for it. This is a good find!

Does changing line 920 from `	if entity_definition.spawn_type == QodotFGDSolidClass.SpawnType.WORLDSPAWN:` to `if entity_definition.spawn_type == QodotFGDSolidClass.SpawnType.GROUP:` change anything for you? I'd accept a PR with this regardless.

**Comment by RealPlanet** [comment]
I created a PR for it. I checked and it seems to be fine even with your proposal. In the end I decided to keep both to make it clear we are considering both options (WORLDSPAWN + GROUP)

**Comment by DeerTears** [comment]
Thanks for your help! 😊
