### ISSUE TITLE
Qodot will not load in Godot beta 16

### ISSUE THREAD

**Issue by nullsquid** [QodotPlugin/Qodot#8]
latest Qodot release won't load in Gv4.0.beta16.mono.official [518b9e580]. OS is windows 10 64 bit. Attached is console log output of errors

![217164536-1b6f08f2-7097-4cf9-aba6-fc0ea0c8d343](https://user-images.githubusercontent.com/6439547/217615872-cf28ca92-65ca-4667-9736-f242785757a2.jpg)

**Comment by EMBYRDEV** [comment]
Since you originally posted this in the qodot 3 plugin issues, can I double check you are using the C# version of the plugin found in this repository and not the old one? 

Also, do you have the dotNet sdk installed as is specified next to the mono build download? 
![image](https://user-images.githubusercontent.com/20043270/217905749-9a585eef-77fb-4ae0-9dd6-122c3fc60119.png)

**Comment by DeerTears** [comment]
This issue should be addressed by #15
